version: '3.9'

services:
  api:
    restart: always
    ports:
      - "8000:8000"
    image: crud-api
    container_name: compose-api
  
  frontend:
    image: frontend

    ports:
      - "3000:3000"
    container_name: compose-front